name: LiminalDB CI

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'crates/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Cargo check (workspace)
        run: cargo check --workspace

      - name: Cargo test (core + store)
        run: |
          cargo test -q -p liminal-core --no-fail-fast
          cargo test -q -p liminal-store --no-fail-fast

