[workspace]
members = [
    "crates/liminal-core",
    "crates/liminal-sensor",
    "crates/liminal-cli",
    "crates/liminal-bridge-abi",
    "crates/liminal-bridge-net",
    "crates/liminal-store",
    "crates/liminal-sal",
    "crates/sal-adapters/sled",
]
resolver = "2"
