[package]
name = "liminal-store"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
crc32fast = "1"
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.11"
thiserror = "1"
parking_lot = "0.12"
liminal-core = { path = "../liminal-core" }
